// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      includereplace: {
        dist: {
          options: {
            prefix: '@@',
            suffix: ''
          },
          src: 'dev/*.html',
          dest: 'build/'
        }
      },
      clean: {
        files: ["build/_*.html", "build/*.js"]
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: "dev/img/",
              src: ["**"],
              dest: "build/img"
            }, {
              expand: true,
              cwd: "dev/fonts/",
              src: ["**"],
              dest: "build/fonts"
            }, {
              expand: true,
              cwd: "dev/js",
              src: ["**"],
              dest: "build/js"
            }, {
              expand: true,
              cwd: "dev/img/svg/",
              src: "*",
              dest: "build/img/svg/",
              filter: "isFile"
            }
          ]
        }
      },
      watch: {
        files: ["dev/*.html", "dev/js/*.js", "dev/img/icons*.png"],
        tasks: ["includereplace", "copy", "clean"]
      }
    });
    require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
    grunt.registerTask("default", ["watch"]);
    return grunt.registerTask("a", ["clean", "includereplace", "copy"]);
  };

}).call(this);
