// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      // includereplace: {
      //   dist: {
      //     options: {
      //       prefix: '@@',
      //       suffix: ''
      //     },
      //     src: 'src/*.html',
      //     dest: 'production/'
      //   }
      // },
      includes: {
        files: {
          src: ["src/*.html"],
          dest: "production",
          flatten: true,
          cwd: ".",
          options: {
            silent: true,
            filenamePrefix: "includes/",
            filenameSuffix: ".html"
          }
        }
      },
      clean: {
        files: ["production/_*.html", "production/*.js", "production/img/"]
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: "src/img/",
              src: ["**"],
              dest: "production/img"
            }, {
              expand: true,
              cwd: "src/fonts/",
              src: ["**"],
              dest: "production/fonts"
            }, {
              expand: true,
              cwd: "src/js",
              src: ["**"],
              dest: "production/js"
            }, {
              expand: true,
              cwd: "src/img/svg/",
              src: "*",
              dest: "production/img/svg/",
              filter: "isFile"
            }
          ]
        }
      },
      watch: {
        files: ["src/*.html", "src/js/*.js", "src/includes/*.html", "src/img/icons*.png"],
        tasks: ["clean", "includes", "copy"]
      }
    });
    require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);
    grunt.registerTask("default", ["watch"]);
    return grunt.registerTask("a", ["clean", "includes", "copy"]);
  };

}).call(this);
